### PR TITLE
Expanded the team names.

### PR DESCRIPTION
**Pull request by kavania2002**
#111

### CODE REVIEW

**Comment by kavania2002** [comment]
#112

**Comment by sakshamj74** [comment]
@kavania2002  Please tell more what mistakes have you corrected?

**Comment by sakshamj74** [comment]
@kavania2002 And have u re-run all the files or some left?

**Comment by kavania2002** [comment]
No I have re-run all the files
Somewhere the array was out of range or too small because of the new season. So had to manage.
But all running now successfully

**Pull request merged**
