### PR TITLE
[Fixes #50] Added toss winners

### LINKED ISSUE #50: Which team won the most tosses

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
### What is the change?
I added the analysis of teams that win and the tosses won by them

### What does it fix/add?
I analyzed matches.csv

### How was it tested?
It was tested by toss-winners column

### Submissions guide:
[x] Have you followed the Contribution guide?
[ x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
[ x] Have you made corresponding changes to the documentation?
[ x] Your submission doesn't break any existing feature.
[ x] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
toss

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Please review my pr. I have solved the error sorry for the inconvenience.

**Comment by sakshamj74** [comment]
@Vrindagupta6828  One more thing what the numbers on the x-axis specify?

**Comment by Vrindagupta6828** [comment]
> @Vrindagupta6828 One more thing what the numbers on the x-axis specify?

the teams are encoded should i add a key?

**Comment by sakshamj74** [comment]
> > @Vrindagupta6828 One more thing what the numbers on the x-axis specify?
> 
> the teams are encoded should i add a key?

Yes, it will be easy to interpret.

**Comment by Vrindagupta6828** [comment]
Ok

**Comment by Vrindagupta6828** [comment]
Capture
@sakshamj74 Is this ok this way as i am unable to plot a table out of a dict.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Can you please tell me how much points you have assigned to me for this issue?

**Pull request merged**
