### PR TITLE
matches held every season

### LINKED ISSUE #58: No. of matches played in each season
please do assign it to me,i forget to ask for it earlier

### PR DESCRIPTION
**Pull request by uddeshyatyagi**
closes #58

### CODE REVIEW

**Comment by sakshamj74** [comment]
@uddeshyatyagi Make a separate file and move your code to that file .

**Comment by uddeshyatyagi** [comment]
@sakshamj74 ,code has been moved to a separate file, please review !!

**Comment by sakshamj74** [comment]
@uddeshyatyagi Also remove your code from Matches.ipynb

**Comment by uddeshyatyagi** [comment]
@sakshamj74, i already removed my code from matches.ipynb, has only added code in a separate file afaik !!

**Comment by uddeshyatyagi** [comment]
Screenshot from 2020-12-14 16-39-47
Screenshot from 2020-12-14 16-39-56

@sakshamj74 in this screenshot you can clearly see that i have only added my code in a separate file and not in matches.ipynb

If there is something which is not okay then please tell me about that again ,have a word of conversation,explain it to me,but don't stay quite for 5-6 days or so.
Thank you !

**Comment by sakshamj74** [comment]
Hey, @uddeshyatyagi Will figure it out by today.

**Pull request merged**
