### PR TITLE
Added top_runners analysis #1

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
Description :
Analyzed "deliveries.csv" to get the Top 5 run-getters(all seasons)
Changes in top_runners.ipynb notebook

Issue : #1

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey, @sakshamj74 Take a look at these changes, Actually, I was facing some conflicts from the previous branch that's why I created a new branch and make a new or. Sorry for the inconvenience if caused.

**Comment by sakshamj74** [comment]
Hey, @kritikaparmar-programmer Can we get top run-getters irrespective of the inning they have played. And please mention total runs on top of each bar in the graph for better readability.
And make a separate file or notebook for your task and commit to the main branch. I don't think there will be any conflicts then.

**Comment by sakshamj74** [comment]
Hey, @kritikaparmar-programmer I just checked. But there are some issues with your plots.
Like in the below plot you are plotting runs scored by batsmen, then how can runs be the same for 5 batsmen and this issue is with 3-4 plots.
Also, put small text on each bar of the graph representing runs scored by batsmen.
And your file structure is fine.
s1

**Comment by kritikaparmar-programmer** [comment]
Hey, @sakshamj74 I took a look at data again for different innings, and when we order them according to the run scored then it is clearly seen that players are having the same runs.
Screenshot 2020-12-12 040018

**Comment by kritikaparmar-programmer** [comment]
Hey, @sakshamj74 please reply. If there is any change you want I'll do it.

**Comment by sakshamj74** [comment]
> Hey, @sakshamj74 please reply. If there is any change you want I'll do it.

@kritikaparmar-programmer  okay will look into it.

**Pull request merged**
