### PR TITLE
Highest team total in each season and Best Batsmen Analysis

### LINKED ISSUE #16: Best Batsmen Analysis
Analyze the performances of some of the best batsmen and show them using some nice plots

### PR DESCRIPTION
**Pull request by Player0109**
I this I have plotted two things
(1) Highest Run scored by each team in an inning in each season.
(2) Which Team Scored Highest Total in each season.

Best Batsmen Analysis:
Did a detailed analysis of ['DA Warner', 'V Kohli', 'R Sharma', 'AD Russell', 'HH Pandya', 'RR Pant']
close #16

### CODE REVIEW

**Comment by Halix267** [comment]
@Player0109 This issue is assigned to me. Give me a day or two to solve this issue.If i am unable to fix this issue the admin will give this issue to you. So can u please close this pr. Although the admin merge your pr but your score will not update as this issue is not belong to you.

**Comment by sakshamj74** [comment]
This is already an assigned issue. Let @Player0109 work on this.You can analyze some other aspect till then.

**Comment by Halix267** [comment]
but  you assigned this issue to me

**Comment by Halix267** [comment]
@sakshamj74 U shoud have told me earlier. Or just give me the deadline before assigning issue to someone else

**Comment by Player0109** [comment]
@sakshamj74 Plz review it.

**Pull request closed without merging**
