### PR TITLE
Analyse two teams

### LINKED ISSUE #4: Analyzing two Teams
Pick your favorite team and the team you dislike most.
Use "matches.csv" and find who win most matches OR Most Mom awards i OR leading run-scorer OR leading wicket-taker in head to head matches.

### PR DESCRIPTION
**Pull request by Halix267**
closes #4 
Analyse two teams (MI & CSK)

### CODE REVIEW

**Comment by Halix267** [comment]
@sakshamj74 Plzz review it.

**Comment by sakshamj74** [comment]
@Halix267 Please make a different file for this as more future work is to be done regarding this. And also add one or two lines of comment explaining your approach.

**Comment by Halix267** [comment]
ok @sakshamj74

**Comment by Halix267** [comment]
Should i remove the work done on Deliveries.ipynb related to this issue  and than create a separate file for this?

**Comment by sakshamj74** [comment]
@Halix267 Yes.

**Pull request closed without merging**
