### PR TITLE
Highest score of team in each season

### LINKED ISSUE #6: HIghest Team Total each season.
Analyze data to get the Highest team score (every season) and plot the result using some innovative and easy to understand plots.

### PR DESCRIPTION
**Pull request by Halix267**
closes #6 
Highest team score each season

### CODE REVIEW

**Comment by Halix267** [comment]
@sakshamj74 I have made the changes in Delieveries.ipynb.Plzz review it.

**Comment by sakshamj74** [comment]
Hey, you have plotted the highest team totals each season and in legends, it is showing Batsman's name. Please correct it.

**Comment by Halix267** [comment]
Ok ok sorry i will correct it

**Comment by sakshamj74** [comment]
@Halix267  Please don't be sorry. It happens.
Guyz please make a separate file of what you are working on Because it is getting difficult to keep track of things as we are all working on the same files. So you can keep the file name related to the task you have performed in the notebook. Like if you are working on top bowlers you can keep the filename as "top_bowlers.ipynb"

**Comment by Halix267** [comment]
@sakshamj74 I have corrected the code . Plzz review it.

**Comment by Halix267** [comment]
@sakshamj74 .Can u tell me when will u assign the points of this pr , If u already assigned the points, but u give me 5 points for this pr as it was the intermediate issue.

**Pull request merged**
