### PR TITLE
Winning by 10 Wickets

### PR DESCRIPTION
**Pull request by kavania2002**
#71 

Actually first I found it easier but while doing it was not. Thanks because I got to learn about Counter Function

Win_by_10

### CODE REVIEW

**Comment by kavania2002** [comment]
#75 

FamousPlayer_SR
SingleMatchSR

**Comment by kavania2002** [comment]
Man for #75 , this calls for a tough problem because I got to learn so many new things. How to handle dataframe and all that. Thanks dude.

**Comment by kavania2002** [comment]
And regarding the 4's and 6's you told in #75, I need to create a separate and will surely work upon that.
And thanks for keep updated score.

**Comment by kavania2002** [comment]
#77 

Wides_Bowled

It was a small contribution so created in deliveries filed only, new file was not needed.

**Comment by sakshamj74** [comment]
Hey, @kavania2002 I think there should be 10 wickets instead of 11 wickets.  
And please update your local repo, add your code, and then commit because it is showing conflicts in Matches.ipynb and it may be due to that you have not added code in the updated repo.
[](url)
ss3

**Comment by kavania2002** [comment]
Yeah you are right.

**Comment by kavania2002** [comment]
I am creating new pull request #86

**Pull request closed without merging**
