### PR TITLE
Adding EDA on IPL Dataset

### LINKED ISSUE #85: EDA on IPL Dataset
I intend on doing a proper EDA
This includes Team analysis,Bowler Analysis,Batsman Analysis,Matches Analysis.
It includes:

1. Team won by Maximum Runs
2. Team won by Maximum wickets
3. Team won by minimum runs
4. Team won by Minimum Wickets
5. Season Which had most number of matches
6. Top Player of the match winners
7. Number of matches in each venue
8. Number of matches played by each team
9. Number of wins per team
10. Champions each season
11. Toss decision
12. Top players of the match
13. Top Umpires
14. Top run scorers in IPL
15. Batsman with most number of boundaries
16. Batsman with most number of sixes
17. Batsman with most number of dot balls
18. Batsman with highest percentage of dot balls
19. Top Bowler-No of Bowls Balled
20. Top Bowlers- No. of Dot balls bowled
21. Bowlers with most extras
22. Most common dismissal types in IPL

Even though these are rather straight forward questions to answer,it is a lot of python code to show it well.Would appreciate if it can be assigned to me and categorised as difficult or intermediate atleast.

### PR DESCRIPTION
**Pull request by ashwanirathee**
This has
1. Team won by Maximum Runs
2. Team won by Maximum wickets
3. Team won by minimum runs
4. Team won by Minimum Wickets
5. Season Which had most number of matches
6. Top Player of the match winners
7. Number of matches in each venue
8. Number of matches played by each team
9. Number of wins per team
10. Champions each season
11. Toss decision
12. Top players of the match
13. Top Umpires
14. Top run scorers in IPL
15. Batsman with most number of boundaries
16. Batsman with most number of sixes
17. Batsman with most number of dot balls
18. Batsman with highest percentage of dot balls
19. Top Bowler-No of Bowls Balled
20. Top Bowlers- No. of Dot balls bowled
21. Bowlers with most extras
22. Most common dismissal types in IPL

### What is the change?

It has EDA of Teams,Batsmen,Bowlers, and Deliveries Analysis
And Closes #85 
### What does it fix/add?

It adds a jupyter notebook

### How was it tested?

I checked it on my system

## Submissions guide:
- [x] Have you followed the [Contribution guide](https://github.com/sakshamj74/IPL-Analysis/blob/main/CONTRIBUTING.md)?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/sakshamj74/IPL-Analysis/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by sakshamj74** [comment]
Hey, @ashwani-rathee a lot of them have been already done. What you can do is look for those aspects which are not done yet. Then work on them instead of working on something which is already done.

**Comment by ashwanirathee** [comment]
Hi @sakshamj74, I checked with closed PRs,and there are 4-5 that have been done I know,But I did 22 of which a lot of it is new.And I am sure if you can give the Plots a look they took a fairly good amount of time to make.If it's possible for you to give me 5 points at least,that would be good enough,then I can move on working on next issues.

**Comment by sakshamj74** [comment]
@ashwani-rathee Look what we can do is. Yes, there are some aspects which are not worked upon earlier. I will suggest you take one or two aspects at a time and raise a issue, and make a pr.
So this will get you get more points. Because what we are doing in this repo I am assigning 5 -10 points for every 1-2 analysis based on their complexity. And it will be unfair to give 5 points for your that much work.
So make a spereate file(with name of file being the aspect your analysing) .If you are working on some already worked issue then you can continue in the same file.
I hope it's good.Feel free to ask about any other queries.

**Comment by ashwanirathee** [comment]
Okay,I'll do that :)

**Pull request closed without merging**
