### PR TITLE
[Fixes #5] Added top 5 all rounders

### LINKED ISSUE #5: Top 5 all Rounders
Analyze "deliveries.csv" to get top all-rounders in IPL history based on wickets taken and runs scored and visualize the results.

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #5

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Please review my pr.

**Comment by sakshamj74** [comment]
@Vrindagupta6828  Please review your code once again because R Sharma and V Kohli in top all-rounders are a bit strange.
Moreover,,in #5  @Player0109  also uploaded some graphs with some criteria as you r(min 1000 runs and 40 wickets) and results are different.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 I know but i also performed the analysis and only this is coming you can check all the calculations

**Comment by sakshamj74** [comment]
@Vrindagupta6828 Let me check this again

**Comment by Vrindagupta6828** [comment]
@sakshamj74 yes sure..thank you

**Comment by Vrindagupta6828** [comment]
@sakshamj74 Did you check?

**Comment by sakshamj74** [comment]
@Vrindagupta6828  I haven't checked yet.I Will let you know tomorrow.

**Comment by sakshamj74** [comment]
@Vrindagupta6828  I analyzed your code.
Actually, notice the last line in this ss. In this you are just printing batsmen with >=1000 runs not updating your data frame which you will be using later.
So you must chnage this line to top_batsmen=top_batsmen[top_batsmen.runs>=1000]
Similar is the case with bowlers. That is why we are getting incorrect results.
s2

**Comment by sakshamj74** [comment]
@Vrindagupta6828 After corrections, I am getting something like this (min 1000 runs and 50 wickets).

s3
Please do the necessary corrections and remove this code from deliveries.ipynb and make a separate file for this as we will be working more on this.

**Comment by Vrindagupta6828** [comment]
@sakshamj74 sure and what should i name that file?

**Comment by sakshamj74** [comment]
@Vrindagupta6828 Anything related to the task you will be doing like "top_5_all_rounders.ipynb"

**Comment by Vrindagupta6828** [comment]
@sakshamj74  Raised another pr please review it.

**Pull request closed without merging**
