### PR TITLE
2020 IPL Data

### PR DESCRIPTION
**Pull request by kavania2002**
#98 
I found the data.

### CODE REVIEW

**Comment by sakshamj74** [comment]
@kavania2002  This is a ball by ball data, right?
Have you found matches data also?
And have you find it online or you have scrapped it?

**Comment by kavania2002** [comment]
@sakshamj74 , yep this is ball by ball. 
No I didn't find matches data.
Thank god that I found online. For the matches I think I can search more or I have to do web scrapping.

**Comment by sakshamj74** [comment]
@kavania2002  Great then keep looking for it, as soon as you find make a pr. I will merge both of them at once.

**Comment by kavania2002** [comment]
Hey @sakshamj74 I found the matches file also.

**Pull request merged**
